spring.application.name=SmartBiz-Spring
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/smart_biz_new?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=ZkYzQnZ4Vm5sT0JzN2dFQmJ1dXh6WjVhV3I2Qk9zZHR4NExUeXJOM3V0U2dJQmFjRm1Yd2p4QnBrU2U5UQ
jwt.expiration=3600000